### ISSUE TITLE
Promise vs Observable

### ISSUE THREAD

**Issue by chriscurnow** [Wakanda/wakanda-javascript-client#10]
It appears this client returns promises rather than observables.

Is there a particular reason for this. Angular2 seems is plugging observables quite strongly.

**Comment by mrblackus** [comment]
Hi,

Wakanda-Client is framework-wagnostic at will, it's designed to work well, whatever the chosen framework. At this time, the more well-established and spread way of dealing with asynchronous tasks are promises, that's why they were chosen.

But there is no lock-in, and we already think about observables when dealing with Angular 2. It's not documented yet, but Wakanda-Client internal HTTP client has public interceptors, and it could be quite easy to make a plugin that catch API results, and transform them into observables.
